export const PREVIEW_ESTIMATE_FIXTURE = {
  id: 'preview-fixture',
  estimate_number: 'E00001',
  created_at: new Date('2026-04-22T12:00:00Z'),
  status: 'SENT' as const,
  subtotal: 1188.10,
  tax_rate: 0.06625,
  tax_amount: 78.71,
  total_amount: 1266.81,
  discount_type: null,
  discount_value: null,
  discount_name: null,
  discount_amount: 0,
  scope_notes: null,
  signature_data: null,
  signature_at: null,
  snapshot_terms: null,
  snapshot_notes: null,
  snapshot_payment_terms: null,
  // R6 (2026-07-22) — mirrors estimateDetailSelect's widened EstimateForPdf: this fixture
  // exercises the legacy lead.customer/service_address fallback (kept null so the existing
  // "Same as billing" / customer-name assertions below are unaffected).
  customer: null,
  service_location: null,
  lead: {
    service_address_line1: null,
    service_address_line2: null,
    service_city: null,
    service_state: null,
    service_zip: null,
    customer: {
      first_name: 'Jane',
      last_name: 'Doe',
      company_name: null,
      email: 'jane.doe@example.com',
      phone: '(555) 123-4567',
      service_locations: [{
        is_primary: true,
        address_line1: '123 Main Street',
        address_line2: null,
        city: 'Hoboken',
        state: 'NJ',
        zip: '07030',
      }],
    },
  },
  line_items: [
    {
      id: 'p1',
      sequence: 1,
      description: 'Item 1\nDescription line',
      item_type: 'MATERIAL' as const,
      quantity: 1,
      unit_price: 499.00,
      is_taxable: true,
      line_total: 499.00,
      discount_type: null,
      discount_value: null,
      discount_amount: 0,
      price_book_item: null,
    },
    {
      id: 'p2',
      sequence: 2,
      description: 'Item 2',
      item_type: 'SERVICE' as const,
      quantity: 2,
      unit_price: 225.00,
      is_taxable: true,
      line_total: 450.00,
      discount_type: null,
      discount_value: null,
      discount_amount: 0,
      price_book_item: null,
    },
    {
      id: 'p3',
      sequence: 3,
      description: 'Item 3\nDescription line',
      item_type: 'SERVICE' as const,
      quantity: 1,
      unit_price: 99.00,
      is_taxable: true,
      // GROSS (quantity × unit_price), matching what calculateTotals persists. This fixture
      // previously stored the NET 89.10, a convention production never uses — which made the
      // PDF reconciliation tests pass against data the app cannot produce, hiding the fact that
      // the templates printed a discounted line's gross amount inside a net subtotal.
      line_total: 99.00,
      discount_type: 'PERCENTAGE' as const,
      discount_value: 10,
      discount_amount: 9.90,
      price_book_item: null,
    },
    {
      id: 'p4',
      sequence: 4,
      description: 'Additional Service',
      item_type: 'SERVICE' as const,
      quantity: 1,
      unit_price: 150.00,
      is_taxable: true,
      line_total: 150.00,
      discount_type: null,
      discount_value: null,
      discount_amount: 0,
      price_book_item: null,
    },
  ],
};

// Invoice PDF template parity — mirrors PREVIEW_ESTIMATE_FIXTURE's shape/customer/line items so the
// two documents preview with the same customer + line items, but exercises the invoice-only rows:
// a deposit credit and a payment, so the preview shows Deposit credit / Payments / Balance Due
// actually reconciling (total_amount − deposit_credit − payments = amount_due).
export const PREVIEW_INVOICE_FIXTURE = {
  id: 'preview-fixture',
  invoice_number: 'I00001',
  created_at: new Date('2026-04-22T12:00:00Z'),
  due_date: new Date('2026-05-06T12:00:00Z'),
  status: 'SENT' as const,
  subtotal: 1188.10,
  discount_amount: 0,
  discount_name: null,
  tax_rate: 0.06625,
  tax_amount: 78.71,
  deposit_credit: 200.00,
  total_amount: 1266.81,
  amount_due: 966.81,
  customer: {
    first_name: 'Jane',
    last_name: 'Doe',
    company_name: null,
    email: 'jane.doe@example.com',
    phone: '(555) 123-4567',
    service_locations: [{
      is_primary: true,
      address_line1: '123 Main Street',
      address_line2: null,
      city: 'Hoboken',
      state: 'NJ',
      zip: '07030',
    }],
  },
  service_location: {
    address_line1: '123 Main Street',
    address_line2: null,
    city: 'Hoboken',
    state: 'NJ',
    zip: '07030',
  },
  line_items: PREVIEW_ESTIMATE_FIXTURE.line_items,
  payments: [
    { amount: 100.00, voided_at: null },
  ],
};
