import { lazy } from 'react';
import { Route } from 'react-router-dom';

import ProtectedRoute from '@/components/ProtectedRoute';

import { moduleV2Routes } from './routes';
import V2AppLayout from './V2AppLayout';

/**
 * The app's route block.
 *
 * Returned as a fragment of <Route> elements so App.tsx can splice it into the
 * existing tree without restructuring it.
 *
 * These routes own the BARE paths (`/leads`, `/jobs`, ...). There is no `/v2`
 * prefix and no feature flag: this is the app. The legacy pages under
 * `src/pages/` still exist as files - 60-odd test files import them - but they
 * are UNROUTED, with the deliberate exception of the four settings tabs that
 * never got a counterpart here (see `routes/settings.routes.tsx`).
 *
 * ADDING A MODULE: create `routes/<module>.routes.tsx` and
 * `routes/<module>.paths.ts`. Both are auto-discovered. Do NOT edit this file,
 * `routes/index.tsx`, `routes/paths.ts` or `uiV2.ts` - they are shared by every
 * module branch, and editing them is exactly what makes parallel branches
 * conflict on merge. See `routes/README.md`.
 *
 * Guards: every route reuses the SAME ProtectedRoute / RequireFeature wrappers
 * the legacy route table carried. Reproducing a page without its guard would
 * change who can reach it, which is a behaviour change, not a restyle. The
 * stacks are asserted mechanically in `__tests__/guardParity.test.ts`.
 *
 * Chrome: everything here nests under V2AppLayout, the kit shell.
 */

const KitReferencePage = lazy(() => import('./_reference/KitReferencePage'));

export function v2Routes() {
  return (
    <>
      {/* The kit's own reference implementation, kept as the visual baseline to
          diff against the kit's jobsPagePreview.html. Not a product page: it
          renders the kit's static fixture data.

          Behind ProtectedRoute despite holding no real data. It is unreleased
          UI, and leaving it open would contradict the rule stated above it. */}
      <Route element={<ProtectedRoute />}>
        <Route element={<V2AppLayout />}>
          <Route path="/_kit-reference" element={<KitReferencePage />} />
        </Route>
      </Route>

      {/* The app root `/` is declared by the Dashboard module, in
          `routes/dashboard.routes.tsx`, and nowhere else. */}

      {/* Every module's own <Route> block, auto-discovered from routes/. */}
      {moduleV2Routes()}
    </>
  );
}
