import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { prisma } from '../lib/prisma';

/**
 * Slice-1 regression guard for the CTM phone-system migration.
 *
 * The migration is hand-authored (never generated by `prisma migrate dev` — the
 * local .env points at the shared staging DB), so this test pins the mandatory
 * security boilerplate: RLS backstop on the new org-scoped table, role-guarded
 * PostgREST revokes on both new tables, idempotent DDL, and the guarded enum
 * additions. If someone regenerates or edits the migration and drops one of
 * these, CI fails here (in the backend job) before the Database job even runs.
 */

const MIGRATION_PATH = join(
  __dirname,
  '../../prisma/migrations/20260709220000_ctm_phone_system/migration.sql',
);

describe('ctm phone system migration', () => {
  const sql = readFileSync(MIGRATION_PATH, 'utf8');

  it('creates both new tables idempotently', () => {
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS "ctm_events"/);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS "phone_numbers"/);
  });

  it('adds the new columns idempotently', () => {
    expect(sql).toMatch(/ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "ctm_account_id" TEXT/);
    expect(sql).toMatch(/ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "ctm_sms_ready" BOOLEAN NOT NULL DEFAULT false/);
    expect(sql).toMatch(/ALTER TABLE "call_sessions" ADD COLUMN IF NOT EXISTS "ctm_call_id" TEXT/);
    expect(sql).toMatch(/ALTER TABLE "call_sessions" ADD COLUMN IF NOT EXISTS "recording_key" TEXT/);
    expect(sql).toMatch(/ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "ctm_sms_id" TEXT/);
  });

  it('enforces the upsert/dedupe unique indexes', () => {
    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS "ctm_events_ctm_event_id_key"/);
    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS "organizations_ctm_account_id_key"/);
    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS "call_sessions_ctm_call_id_key"/);
    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS "messages_ctm_sms_id_key"/);
    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS "phone_numbers_organization_id_e164_key"/);
  });

  it('applies the tenant RLS backstop to phone_numbers (fail-closed pattern)', () => {
    expect(sql).toMatch(/ALTER TABLE "phone_numbers" ENABLE ROW LEVEL SECURITY/);
    expect(sql).toMatch(/ALTER TABLE "phone_numbers" FORCE ROW LEVEL SECURITY/);
    expect(sql).toMatch(/DROP POLICY IF EXISTS "tenant_isolation" ON "phone_numbers"/);
    expect(sql).toMatch(/CREATE POLICY "tenant_isolation" ON "phone_numbers"/);
    const policyBlock = sql.slice(sql.indexOf('CREATE POLICY "tenant_isolation" ON "phone_numbers"'));
    expect(policyBlock).toMatch(/USING \(current_setting\('app\.bypass_rls', true\) = 'on' OR "organization_id" = NULLIF\(current_setting\('app\.current_org_id', true\), ''\)::uuid\)/);
    expect(policyBlock).toMatch(/WITH CHECK \(current_setting\('app\.bypass_rls', true\) = 'on' OR "organization_id" = NULLIF\(current_setting\('app\.current_org_id', true\), ''\)::uuid\)/);
  });

  it('does NOT apply a tenant policy to the global ctm_events table (stripe_events precedent)', () => {
    expect(sql).not.toMatch(/CREATE POLICY[^;]*"ctm_events"/);
  });

  it('revokes anon/authenticated grants on both new tables behind role-existence guards', () => {
    expect(sql).toMatch(/IF EXISTS \(SELECT 1 FROM pg_roles WHERE rolname = 'anon'\)/);
    expect(sql).toMatch(/IF EXISTS \(SELECT 1 FROM pg_roles WHERE rolname = 'authenticated'\)/);
    expect(sql).toMatch(/REVOKE ALL PRIVILEGES ON public\.ctm_events, public\.phone_numbers FROM anon/);
    expect(sql).toMatch(/REVOKE ALL PRIVILEGES ON public\.ctm_events, public\.phone_numbers FROM authenticated/);
  });

  it('adds the new enum value guarded with IF NOT EXISTS', () => {
    expect(sql).toMatch(/ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'COMMUNICATION'/);
  });
});

describe('ctm prisma delegates (global test mock)', () => {
  it('exposes the new model delegates used by the webhook/ingest paths', () => {
    /* eslint-disable @typescript-eslint/no-explicit-any */
    const p = prisma as any;
    expect(typeof p.ctmEvent.create).toBe('function');
    expect(typeof p.ctmEvent.findUnique).toBe('function');
    expect(typeof p.phoneNumber.findMany).toBe('function');
    expect(typeof p.phoneNumber.upsert).toBe('function');
    expect(typeof p.callSession.upsert).toBe('function');
    expect(typeof p.callSession.findUnique).toBe('function');
    expect(typeof p.callSession.update).toBe('function');
    expect(typeof p.message.upsert).toBe('function');
    expect(typeof p.message.findFirst).toBe('function');
    expect(typeof p.message.update).toBe('function');
    expect(typeof p.messageThread.update).toBe('function');
    expect(typeof p.$executeRawUnsafe).toBe('function');
    /* eslint-enable @typescript-eslint/no-explicit-any */
  });
});
