-- Non-destructive full sync: cross-join every organization against the CURRENT
-- DEFAULT_GRANTS (backend/src/lib/permissions/defaultGrants.ts), inserting only rows
-- that don't already exist. Never updates or deletes existing role_permissions rows —
-- per-org customizations and any grants outside DEFAULT_GRANTS are left untouched.
--
-- Root cause: no code path seeds role_permissions when an org is created, and prior
-- backfills (20260528204625_add_role_permissions, 20260707000000_backfill_reference_data_reads)
-- only ever covered the grants that existed in DEFAULT_GRANTS at the time they were
-- written. DEFAULT_GRANTS has grown since (Phase B RBAC overhaul, #527/#428 fix, etc.)
-- without a re-sync, so real orgs (confirmed via direct query on staging + prod) are
-- missing large swaths of grants their role should have — e.g. TECHNICIAN's own-job
-- read grant is entirely absent for every non-demo org on staging.
--
-- Generated via: cd backend && npx tsx src/scripts/check-role-permission-drift.ts --emit-sql
-- Idempotent (ON CONFLICT DO NOTHING) — safe to run more than once.
INSERT INTO role_permissions (id, organization_id, role, action, subject, conditions, created_at, updated_at)
SELECT
  gen_random_uuid(),
  o.id,
  g.role,
  g.action,
  g.subject,
  g.conditions::jsonb,
  NOW(),
  NOW()
FROM organizations o
CROSS JOIN (VALUES
  ('SALES','read','Task',NULL),
  ('SALES','create','Task',NULL),
  ('SALES','update','Task',NULL),
  ('SALES','delete','Task',NULL),
  ('SALES','read','Customer',NULL),
  ('SALES','update','Customer',NULL),
  ('SALES','export','Customer',NULL),
  ('SALES','create','Lead',NULL),
  ('SALES','read','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','update','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','contact','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','mark_lost','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','cancel','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','delete','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','schedule_walkthrough','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','perform_walkthrough','Lead','{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('SALES','create','Estimate',NULL),
  ('SALES','read','Estimate','{"lead":{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}}'),
  ('SALES','update','Estimate',NULL),
  ('SALES','delete','Estimate',NULL),
  ('SALES','send','Estimate',NULL),
  ('SALES','cancel','Estimate',NULL),
  ('SALES','duplicate','Estimate',NULL),
  ('SALES','revise','Estimate',NULL),
  ('SALES','read','Job','{"estimate":{"lead":{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}}}'),
  ('SALES','read','Invoice','{"job":{"estimate":{"lead":{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}}}}'),
  ('SALES','manage_lines','Invoice','{"job":{"estimate":{"lead":{"lead_assignees":{"some":{"user_id":"{{userId}}"}}}}}}'),
  ('SALES','read','PriceBook',NULL),
  ('SALES','create','PriceBook',NULL),
  ('SALES','update','PriceBook',NULL),
  ('SALES','delete','PriceBook',NULL),
  ('SALES','read','Tag',NULL),
  ('SALES','create','Tag',NULL),
  ('SALES','read','Department',NULL),
  ('SALES','read','StateTaxRate',NULL),
  ('SALES','read','AppSetting',NULL),
  ('SALES','read','Organization',NULL),
  ('SALES','create','Attachment',NULL),
  ('SALES','read','Attachment',NULL),
  ('SALES','update','Attachment',NULL),
  ('SALES','delete','Attachment',NULL),
  ('SALES','read','Inventory',NULL),
  ('SALES','read','Communication',NULL),
  ('DISPATCHER','read','Task',NULL),
  ('DISPATCHER','create','Task',NULL),
  ('DISPATCHER','update','Task',NULL),
  ('DISPATCHER','delete','Task',NULL),
  ('DISPATCHER','read','Dashboard',NULL),
  ('DISPATCHER','create','Customer',NULL),
  ('DISPATCHER','read','Customer',NULL),
  ('DISPATCHER','update','Customer',NULL),
  ('DISPATCHER','delete','Customer',NULL),
  ('DISPATCHER','export','Customer',NULL),
  ('DISPATCHER','archive','Customer',NULL),
  ('DISPATCHER','create','Lead',NULL),
  ('DISPATCHER','read','Lead',NULL),
  ('DISPATCHER','update','Lead',NULL),
  ('DISPATCHER','assign','Lead',NULL),
  ('DISPATCHER','contact','Lead',NULL),
  ('DISPATCHER','mark_lost','Lead',NULL),
  ('DISPATCHER','cancel','Lead',NULL),
  ('DISPATCHER','delete','Lead',NULL),
  ('DISPATCHER','schedule_walkthrough','Lead',NULL),
  ('DISPATCHER','perform_walkthrough','Lead',NULL),
  ('DISPATCHER','read','Estimate',NULL),
  ('DISPATCHER','record_payment','Estimate',NULL),
  ('DISPATCHER','waive_deposit','Estimate',NULL),
  ('DISPATCHER','create','Job',NULL),
  ('DISPATCHER','read','Job',NULL),
  ('DISPATCHER','update','Job',NULL),
  ('DISPATCHER','delete','Job',NULL),
  ('DISPATCHER','assign','Job',NULL),
  ('DISPATCHER','unassign','Job',NULL),
  ('DISPATCHER','en_route','Job',NULL),
  ('DISPATCHER','arrive','Job',NULL),
  ('DISPATCHER','start','Job',NULL),
  ('DISPATCHER','complete','Job',NULL),
  ('DISPATCHER','cancel','Job',NULL),
  ('DISPATCHER','create','Invoice',NULL),
  ('DISPATCHER','read','Invoice',NULL),
  ('DISPATCHER','update','Invoice',NULL),
  ('DISPATCHER','manage_lines','Invoice',NULL),
  ('DISPATCHER','delete','Invoice',NULL),
  ('DISPATCHER','send','Invoice',NULL),
  ('DISPATCHER','record_payment','Invoice',NULL),
  ('DISPATCHER','read','PriceBook',NULL),
  ('DISPATCHER','read','Tag',NULL),
  ('DISPATCHER','create','Tag',NULL),
  ('DISPATCHER','read','Department',NULL),
  ('DISPATCHER','read','Report',NULL),
  ('DISPATCHER','read','StateTaxRate',NULL),
  ('DISPATCHER','read','AppSetting',NULL),
  ('DISPATCHER','read','Organization',NULL),
  ('DISPATCHER','read','User',NULL),
  ('DISPATCHER','create','Attachment',NULL),
  ('DISPATCHER','read','Attachment',NULL),
  ('DISPATCHER','update','Attachment',NULL),
  ('DISPATCHER','delete','Attachment',NULL),
  ('DISPATCHER','read','Inventory',NULL),
  ('DISPATCHER','create','Inventory',NULL),
  ('DISPATCHER','update','Inventory',NULL),
  ('DISPATCHER','delete','Inventory',NULL),
  ('DISPATCHER','read','Communication',NULL),
  ('DISPATCHER','create','Communication',NULL),
  ('DISPATCHER','update','Communication',NULL),
  ('DISPATCHER','delete','Communication',NULL),
  ('DISPATCHER','read','Location',NULL),
  ('DISPATCHER','read','ServicePlan',NULL),
  ('DISPATCHER','create','ServicePlan',NULL),
  ('DISPATCHER','update','ServicePlan',NULL),
  ('DISPATCHER','delete','ServicePlan',NULL),
  ('TECHNICIAN','read','Task',NULL),
  ('TECHNICIAN','create','Task',NULL),
  ('TECHNICIAN','update','Task',NULL),
  ('TECHNICIAN','read','Lead','{"walkthrough_performers":{"some":{"user_id":"{{userId}}"}}}'),
  ('TECHNICIAN','perform_walkthrough','Lead','{"walkthrough_performers":{"some":{"user_id":"{{userId}}"}}}'),
  ('TECHNICIAN','read','Job','{"assignees":{"some":{"user_id":"{{userId}}"}}}'),
  ('TECHNICIAN','read','Department',NULL),
  ('TECHNICIAN','read','AppSetting',NULL),
  ('TECHNICIAN','read','Organization',NULL),
  ('TECHNICIAN','create','Attachment',NULL),
  ('TECHNICIAN','read','Attachment',NULL),
  ('SALES','read','Notification','{"recipient_id":"{{userId}}"}'),
  ('SALES','update','Notification','{"recipient_id":"{{userId}}"}'),
  ('SALES','delete','Notification','{"recipient_id":"{{userId}}"}'),
  ('DISPATCHER','read','Notification','{"recipient_id":"{{userId}}"}'),
  ('DISPATCHER','update','Notification','{"recipient_id":"{{userId}}"}'),
  ('DISPATCHER','delete','Notification','{"recipient_id":"{{userId}}"}'),
  ('TECHNICIAN','read','Notification','{"recipient_id":"{{userId}}"}'),
  ('TECHNICIAN','update','Notification','{"recipient_id":"{{userId}}"}'),
  ('TECHNICIAN','delete','Notification','{"recipient_id":"{{userId}}"}')
) AS g(role, action, subject, conditions)
ON CONFLICT (organization_id, role, action, subject) DO NOTHING;
