// Seed dataset for the mock-first Call Tracking report — relocated verbatim
// from the retired Communication mock (lib/api/_mock/communication) when #229
// switched the Communication seam to the live API. This report's own mock
// retirement is tracked by #230 (Reports aggregation); until then it keeps
// generating its demo history from these 8 calls + customer roster.

import type { CallSession } from '@/lib/api/communication-shared/phone-calls';
import type { PhoneCustomer } from '@/lib/api/communication-shared/phone-customers';

// Relative to "now" in the prototype the times are just illustrative strings.
export const calls: CallSession[] = [
  {
    id: "call_001",
    direction: "inbound",
    fromNumber: "+12125551042",
    toNumber: "+17185550100",
    trackingSource: "Google Ads · Locksmith",
    status: "completed",
    answeredBy: { kind: "csr", id: "agent_lena" },
    startedAt: "2026-05-28T14:32:00Z",
    durationSec: 247,
    customerId: "cust_rolex",
    jobId: "job_1850",
    jobLabel: "J-1850",
    disposition: "booked",
    sentiment: "positive",
    summary:
      "Daniel (Rolex FM) confirmed vault corridor re-key for Thu 8am. Asked for COI before arrival.",
    transcriptPreview:
      "…yes Thursday morning works, can you send the certificate of insurance to facilities@…",
    hasRecording: true,
    qaScore: 96,
    callFlow: "Main IVR → CSR",
    tags: ["VIP", "Booked"],
    revenue: 1840,
  },
  {
    id: "call_002",
    direction: "inbound",
    fromNumber: "+19175552233",
    toNumber: "+17185550100",
    trackingSource: "Organic · Main line",
    status: "missed",
    answeredBy: { kind: "none" },
    startedAt: "2026-05-28T15:10:00Z",
    customerId: "cust_equinox",
    summary: "Missed call — auto text-back sent. In callback queue.",
    hasRecording: false,
    callFlow: "Forward to Emanuel",
    tags: ["Callback"],
    revenue: 0,
  },
  {
    id: "call_003",
    direction: "inbound",
    fromNumber: "+16465554417",
    toNumber: "+17185550100",
    trackingSource: "Yelp",
    status: "voicemail",
    answeredBy: { kind: "voicemail" },
    startedAt: "2026-05-28T13:02:00Z",
    durationSec: 38,
    customerId: "cust_hyc",
    leadId: "lead_003",
    linkedLead: { id: "lead_003", leadNumber: "L00003" },
    disposition: "quote_requested",
    sentiment: "neutral",
    summary:
      "Greg left VM: kitchen sink rough-in leaking under unit 1402, wants quote this week.",
    transcriptPreview:
      "…hey it's Greg in 1402, there's water under the sink again, give me a call about a quote…",
    hasRecording: true,
    reviewFlag: "Unit # low confidence (1402?)",
    callFlow: "Voicemail",
    tags: ["Quote"],
    revenue: 0,
  },
  {
    id: "call_004",
    direction: "outbound",
    fromNumber: "+17185550100",
    toNumber: "+12125557781",
    status: "completed",
    answeredBy: { kind: "csr", id: "agent_marco" },
    startedAt: "2026-05-28T11:48:00Z",
    durationSec: 415,
    customerId: "cust_tiktok",
    jobId: "job_1853",
    jobLabel: "J-1853",
    disposition: "quote_given",
    sentiment: "neutral",
    summary:
      "Estimate follow-up for Floor 14 access-control retrofit. Priya reviewing internally, decision next week.",
    transcriptPreview:
      "…I'll send the revised estimate over today, give it a look and we can lock in a date…",
    hasRecording: true,
    qaScore: 88,
    callFlow: "Outbound · CSR",
    tags: ["Estimate"],
    revenue: 373.84,
  },
  {
    id: "call_005",
    direction: "inbound",
    fromNumber: "+18005550147",
    toNumber: "+17185550100",
    trackingSource: "Unknown",
    status: "completed",
    answeredBy: { kind: "ai", id: "agent_ai_rosa" },
    startedAt: "2026-05-28T02:14:00Z",
    durationSec: 92,
    disposition: "spam",
    sentiment: "neutral",
    summary: "After-hours AI receptionist screened a solicitation. No action.",
    transcriptPreview:
      "…we're not interested in marketing services, please remove this number from your list…",
    hasRecording: true,
    qaScore: 90,
    callFlow: "AI Receptionist",
    tags: ["Spam"],
    revenue: 0,
  },
  {
    id: "call_006",
    direction: "inbound",
    fromNumber: "+12125559090",
    toNumber: "+17185550100",
    trackingSource: "Main line",
    status: "completed",
    answeredBy: { kind: "ai", id: "agent_ai_rosa" },
    startedAt: "2026-05-28T19:40:00Z",
    durationSec: 176,
    customerId: "cust_tiffany",
    jobId: "job_1868",
    jobLabel: "J-1868",
    disposition: "after_hours_emergency",
    sentiment: "negative",
    summary:
      "After-hours: Tiffany vault won't secure. AI triaged as emergency, escalated to on-call + captured authorization.",
    transcriptPreview:
      "…the vault door isn't throwing the bolt and we close in twenty minutes, we need someone now…",
    hasRecording: true,
    qaScore: 84,
    callFlow: "AI Receptionist → On-call",
    tags: ["Emergency", "Escalated"],
    revenue: 9718.15,
  },
  {
    id: "call_007",
    direction: "inbound",
    fromNumber: "+17185550199",
    toNumber: "+17185550100",
    trackingSource: "Facebook · HVAC",
    status: "missed",
    answeredBy: { kind: "none" },
    startedAt: "2026-05-28T16:05:00Z",
    customerId: "cust_mcd",
    summary: "Missed — Spanish-preferred contact. Bilingual text-back sent.",
    hasRecording: false,
    callFlow: "Forward to Emanuel",
    tags: ["Callback", "ES"],
    revenue: 0,
  },
  {
    id: "call_008",
    direction: "outbound",
    fromNumber: "+17185550100",
    toNumber: "+19175552233",
    status: "completed",
    answeredBy: { kind: "csr", id: "agent_lena" },
    startedAt: "2026-05-27T18:22:00Z",
    durationSec: 76,
    customerId: "cust_equinox",
    leadId: "lead_008",
    linkedLead: { id: "lead_008", leadNumber: "L00008" },
    disposition: "follow_up",
    sentiment: "positive",
    summary: "Returned missed call from Equinox — scheduled site walk for next Tue.",
    transcriptPreview:
      "…great, let's do Tuesday at ten for the site walk, I'll text you the arrival window…",
    hasRecording: true,
    qaScore: 93,
    callFlow: "Outbound · CSR",
    tags: ["Callback"],
    revenue: 0,
  },
];

export const customers: PhoneCustomer[] = [
  {
    id: "cust_rolex",
    name: "Rolex 5th Ave",
    type: "commercial",
    site: "665 Fifth Ave, NY · Vault corridor",
    membershipTier: "Priority SLA",
    slaProfile: "4h response",
    linkedJobIds: ["job_1850"],
    contacts: [
      {
        id: "ct_rolex_fm",
        name: "Daniel Cohen",
        role: "Facilities Manager",
        preferredLang: "en",
        channels: [
          { id: "ch_rolex_p", kind: "phone", value: "+12125551042", label: "Direct", consented: true },
          { id: "ch_rolex_s", kind: "sms", value: "+12125551042", label: "Mobile", consented: true },
        ],
      },
    ],
  },
  {
    id: "cust_mcd",
    name: "McDonald's Atlantic Ave",
    type: "commercial",
    site: "395 Flatbush Ave Ext, Brooklyn · Rooftop unit #2",
    linkedJobIds: ["job_1851"],
    contacts: [
      {
        id: "ct_mcd_gm",
        name: "Rosa Méndez",
        role: "General Manager",
        preferredLang: "es",
        channels: [
          { id: "ch_mcd_p", kind: "phone", value: "+17185550199", label: "Store", consented: true },
          { id: "ch_mcd_s", kind: "sms", value: "+17185550199", consented: true },
        ],
      },
    ],
  },
  {
    id: "cust_tiktok",
    name: "TikTok TriBeCa Office",
    type: "commercial",
    site: "151 Hudson St, NY · Floor 14 access control",
    membershipTier: "Enterprise",
    linkedJobIds: ["job_1853"],
    contacts: [
      {
        id: "ct_tiktok_sec",
        name: "Priya Anand",
        role: "Security Lead",
        preferredLang: "en",
        channels: [
          { id: "ch_tt_p", kind: "phone", value: "+12125557781", label: "Direct", consented: true },
        ],
      },
    ],
  },
  {
    id: "cust_equinox",
    name: "Equinox Hudson Yards",
    type: "commercial",
    site: "33 Hudson Yards, NY · Lobby 1 access control",
    linkedJobIds: ["job_1862"],
    contacts: [
      {
        id: "ct_eqx_ops",
        name: "Marcus Webb",
        role: "Building Ops",
        preferredLang: "en",
        channels: [
          { id: "ch_eqx_p", kind: "phone", value: "+19175552233", label: "Mobile", consented: true },
          { id: "ch_eqx_s", kind: "sms", value: "+19175552233", consented: true },
        ],
      },
    ],
  },
  {
    id: "cust_tiffany",
    name: "Tiffany & Co · 5th Ave",
    type: "commercial",
    site: "727 Fifth Ave, NY · Vault retrofit",
    membershipTier: "Priority SLA",
    linkedJobIds: ["job_1868"],
    contacts: [
      {
        id: "ct_tif_fm",
        name: "Helen Park",
        role: "Facilities",
        preferredLang: "en",
        channels: [
          { id: "ch_tif_p", kind: "phone", value: "+12125559090", consented: true },
        ],
      },
    ],
  },
  {
    id: "cust_hyc",
    name: "Hudson Yards Condo 12B",
    type: "residential",
    site: "517 W 35th St, NY · Unit 1402",
    linkedJobIds: ["job_1845"],
    contacts: [
      {
        id: "ct_hyc_owner",
        name: "Greg Sanders",
        role: "Owner",
        preferredLang: "en",
        channels: [
          { id: "ch_hyc_p", kind: "phone", value: "+16465554417", label: "Mobile", consented: false },
        ],
      },
    ],
  },

  // ── Additional commercial accounts (broaden the call-history demo set). ──
  {
    id: "cust_sephora",
    name: "Sephora SoHo",
    type: "commercial",
    site: "555 Broadway, NY · Stockroom door hardware",
    contacts: [
      {
        id: "ct_sephora_om",
        name: "Aisha Bello",
        role: "Operations Manager",
        preferredLang: "en",
        channels: [{ id: "ch_sephora_p", kind: "phone", value: "+12125553311", label: "Store", consented: true }],
      },
    ],
  },
  {
    id: "cust_chase",
    name: "Chase Branch · Midtown",
    type: "commercial",
    site: "410 Madison Ave, NY · Vestibule + ATM lobby",
    membershipTier: "Priority SLA",
    contacts: [
      {
        id: "ct_chase_fm",
        name: "Robert Kang",
        role: "Facilities",
        preferredLang: "en",
        channels: [{ id: "ch_chase_p", kind: "phone", value: "+19295554820", label: "Direct", consented: true }],
      },
    ],
  },
  {
    id: "cust_wework",
    name: "WeWork Bryant Park",
    type: "commercial",
    site: "54 W 40th St, NY · Floor 6 suite locks",
    contacts: [
      {
        id: "ct_wework_cm",
        name: "Dana Liu",
        role: "Community Manager",
        preferredLang: "en",
        channels: [{ id: "ch_wework_p", kind: "phone", value: "+16465557240", label: "Front desk", consented: true }],
      },
    ],
  },
  {
    id: "cust_nyu",
    name: "NYU Langone Facilities",
    type: "commercial",
    site: "550 1st Ave, NY · Wing C access control",
    membershipTier: "Enterprise",
    contacts: [
      {
        id: "ct_nyu_fm",
        name: "Carlos Vega",
        role: "Facilities Engineer",
        preferredLang: "en",
        channels: [{ id: "ch_nyu_p", kind: "phone", value: "+12125558890", label: "Direct", consented: true }],
      },
    ],
  },
  {
    id: "cust_wholefoods",
    name: "Whole Foods Tribeca",
    type: "commercial",
    site: "270 Greenwich St, NY · Loading dock gate",
    contacts: [
      {
        id: "ct_wf_gm",
        name: "Nina Park",
        role: "Store Manager",
        preferredLang: "en",
        channels: [{ id: "ch_wf_p", kind: "phone", value: "+19175556612", label: "Store", consented: true }],
      },
    ],
  },
  {
    id: "cust_brooklynroasting",
    name: "Brooklyn Roasting Co.",
    type: "commercial",
    site: "25 Jay St, Brooklyn · Roastery rear entrance",
    contacts: [
      {
        id: "ct_br_owner",
        name: "Tom Hayes",
        role: "Owner",
        preferredLang: "en",
        channels: [{ id: "ch_br_p", kind: "phone", value: "+17185554409", label: "Mobile", consented: true }],
      },
    ],
  },
  {
    id: "cust_peloton",
    name: "Peloton Studios NY",
    type: "commercial",
    site: "370 10th Ave, NY · Studio floor access",
    membershipTier: "Priority SLA",
    contacts: [
      {
        id: "ct_peloton_sec",
        name: "Maya Cohen",
        role: "Security Lead",
        preferredLang: "en",
        channels: [{ id: "ch_peloton_p", kind: "phone", value: "+12125551177", label: "Direct", consented: true }],
      },
    ],
  },
  {
    id: "cust_standard",
    name: "The Standard High Line",
    type: "commercial",
    site: "848 Washington St, NY · Guest room re-key",
    contacts: [
      {
        id: "ct_standard_fm",
        name: "Olivia Grant",
        role: "Facilities",
        preferredLang: "en",
        channels: [{ id: "ch_standard_p", kind: "phone", value: "+16465552093", label: "Front desk", consented: true }],
      },
    ],
  },
];
