ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "scopes" JSONB;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "scopes" JSONB;
ALTER TABLE "scope_presets" ADD COLUMN IF NOT EXISTS "is_taxable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "scope_presets" ADD COLUMN IF NOT EXISTS "internal_cost" DECIMAL(12,2);
