-- Additive enum values for lead/walkthrough automation triggers.
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'LEAD_ASSIGNED';
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH_SCHEDULED';
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH_RESCHEDULED';
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH_COMPLETED';
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH_CANCELLED';
ALTER TYPE "AutomationTriggerType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH_PERFORMER_ASSIGNED';
